vlib work
vcom  HDL_ANN_pkg.vhd
vcom  L1.vhd
vcom  L2.vhd
vcom  L3.vhd
vcom  Enabled_Subsystem.vhd
vcom  Subsystem.vhd
vcom  Subsystem1.vhd
vcom  Subsystem2.vhd
vcom  Subsystem3.vhd
vcom  Subsystem5.vhd
vcom  Enabled_Subsystem1.vhd
vcom  HDL_ANN.vhd
