-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\HDL_ANN_pkg.vhd
-- Created: 2022-05-21 11:54:13
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDL_ANN_pkg IS
  TYPE vector_of_std_logic_vector18 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(17 DOWNTO 0);
  TYPE matrix_of_std_logic_vector18 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(17 DOWNTO 0);
  TYPE vector_of_signed36 IS ARRAY (NATURAL RANGE <>) OF signed(35 DOWNTO 0);
  TYPE vector_of_signed18 IS ARRAY (NATURAL RANGE <>) OF signed(17 DOWNTO 0);
  TYPE matrix_of_signed18 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(17 DOWNTO 0);
  TYPE vector_of_std_logic_vector73 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(72 DOWNTO 0);
  TYPE vector_of_signed55 IS ARRAY (NATURAL RANGE <>) OF signed(54 DOWNTO 0);
  TYPE vector_of_signed73 IS ARRAY (NATURAL RANGE <>) OF signed(72 DOWNTO 0);
  TYPE vector_of_std_logic_vector92 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(91 DOWNTO 0);
  TYPE matrix_of_std_logic_vector110 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(109 DOWNTO 0);
  TYPE vector_of_signed19 IS ARRAY (NATURAL RANGE <>) OF signed(18 DOWNTO 0);
  TYPE vector_of_signed92 IS ARRAY (NATURAL RANGE <>) OF signed(91 DOWNTO 0);
  TYPE vector_of_signed91 IS ARRAY (NATURAL RANGE <>) OF signed(90 DOWNTO 0);
  TYPE vector_of_signed110 IS ARRAY (NATURAL RANGE <>) OF signed(109 DOWNTO 0);
  TYPE vector_of_signed109 IS ARRAY (NATURAL RANGE <>) OF signed(108 DOWNTO 0);
  TYPE vector_of_std_logic_vector91 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(90 DOWNTO 0);
  TYPE vector_of_std_logic_vector110 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(109 DOWNTO 0);
  TYPE matrix_of_std_logic_vector128 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(127 DOWNTO 0);
  TYPE vector_of_signed128 IS ARRAY (NATURAL RANGE <>) OF signed(127 DOWNTO 0);
  TYPE vector_of_signed127 IS ARRAY (NATURAL RANGE <>) OF signed(126 DOWNTO 0);
  TYPE vector_of_std_logic_vector74 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(73 DOWNTO 0);
  TYPE vector_of_signed74 IS ARRAY (NATURAL RANGE <>) OF signed(73 DOWNTO 0);
  TYPE matrix_of_signed91 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(90 DOWNTO 0);
  TYPE matrix_of_signed110 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(109 DOWNTO 0);
  TYPE matrix_of_signed128 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(127 DOWNTO 0);
END HDL_ANN_pkg;

