-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Subsystem_Reference.vhd
-- Created: 2022-05-21 15:41:35
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_Reference
-- Source Path: ANN/HDL_ANN/Train/Subsystem Reference
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_ANN_pkg.ALL;

ENTITY Subsystem_Reference IS
  PORT( w                                 :   IN    matrix_of_std_logic_vector18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
        a                                 :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
        e                                 :   IN    vector_of_std_logic_vector73(0 TO 1);  -- sfix73_En48 [2]
        b                                 :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        alpha                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        b_1                               :   OUT   vector_of_std_logic_vector92(0 TO 1);  -- sfix92_En66 [2]
        w_1                               :   OUT   matrix_of_std_logic_vector110(0 TO 1, 0 TO 3)  -- sfix110_En78 [2x4]
        );
END Subsystem_Reference;


ARCHITECTURE rtl OF Subsystem_Reference IS

  -- Signals
  SIGNAL b_signed                         : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL e_signed                         : vector_of_signed73(0 TO 1);  -- sfix73_En48 [2]
  SIGNAL alpha_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL Product1_cast                    : vector_of_signed19(0 TO 1);  -- sfix19_En18 [2]
  SIGNAL Product1_mul_temp                : vector_of_signed92(0 TO 1);  -- sfix92_En66 [2]
  SIGNAL Product1_out1                    : vector_of_signed91(0 TO 1);  -- sfix91_En66 [2]
  SIGNAL Subtract1_sub_cast               : vector_of_signed92(0 TO 1);  -- sfix92_En66 [2]
  SIGNAL Subtract1_sub_cast_1             : vector_of_signed92(0 TO 1);  -- sfix92_En66 [2]
  SIGNAL Subtract1_out1                   : vector_of_signed92(0 TO 1);  -- sfix92_En66 [2]
  SIGNAL w_signed                         : matrix_of_signed18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
  SIGNAL c11_w                            : vector_of_signed18(0 TO 7);  -- sfix18_En12 [8]
  SIGNAL a_signed                         : vector_of_signed18(0 TO 3);  -- sfix18_En12 [4]
  SIGNAL Transpose_out1                   : vector_of_signed18(0 TO 3);  -- sfix18_En12 [4]
  SIGNAL selector_out                     : vector_of_std_logic_vector73(0 TO 7);  -- ufix73 [8]
  SIGNAL selector_out_1                   : vector_of_signed73(0 TO 7);  -- sfix73_En48 [8]
  SIGNAL s                                : vector_of_signed73(0 TO 7);  -- sfix73_En48 [8]
  SIGNAL selector_out_2                   : vector_of_signed18(0 TO 7);  -- sfix18_En12 [8]
  SIGNAL s_1                              : vector_of_signed18(0 TO 7);  -- sfix18_En12 [8]
  SIGNAL MMul_dot_product_out             : vector_of_signed91(0 TO 7);  -- sfix91_En60 [8]
  SIGNAL Product_cast                     : vector_of_signed19(0 TO 7);  -- sfix19_En18 [8]
  SIGNAL Product_mul_temp                 : vector_of_signed110(0 TO 7);  -- sfix110_En78 [8]
  SIGNAL c7_Product_out1                  : vector_of_signed109(0 TO 7);  -- sfix109_En78 [8]
  SIGNAL Subtract_sub_cast                : vector_of_signed110(0 TO 7);  -- sfix110_En78 [8]
  SIGNAL Subtract_sub_cast_1              : vector_of_signed110(0 TO 7);  -- sfix110_En78 [8]
  SIGNAL c11_Subtract_out1                : vector_of_signed110(0 TO 7);  -- sfix110_En78 [8]
  SIGNAL Subtract_out1                    : matrix_of_signed110(0 TO 1, 0 TO 3);  -- sfix110_En78 [2x4]

BEGIN
  outputgen8: FOR k IN 0 TO 1 GENERATE
    b_signed(k) <= signed(b(k));
  END GENERATE;

  outputgen7: FOR k IN 0 TO 1 GENERATE
    e_signed(k) <= signed(e(k));
  END GENERATE;

  alpha_unsigned <= unsigned(alpha);


  Product1_out1_gen: FOR t_0 IN 0 TO 1 GENERATE
    Product1_cast(t_0) <= signed(resize(alpha_unsigned, 19));
    Product1_mul_temp(t_0) <= e_signed(t_0) * Product1_cast(t_0);
    Product1_out1(t_0) <= Product1_mul_temp(t_0)(90 DOWNTO 0);
  END GENERATE Product1_out1_gen;



  Subtract1_out1_gen: FOR t_01 IN 0 TO 1 GENERATE
    Subtract1_sub_cast(t_01) <= resize(b_signed(t_01) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 92);
    Subtract1_sub_cast_1(t_01) <= resize(Product1_out1(t_01), 92);
    Subtract1_out1(t_01) <= Subtract1_sub_cast(t_01) - Subtract1_sub_cast_1(t_01);
  END GENERATE Subtract1_out1_gen;


  outputgen6: FOR k IN 0 TO 1 GENERATE
    b_1(k) <= std_logic_vector(Subtract1_out1(k));
  END GENERATE;

  outputgen4: FOR k IN 0 TO 1 GENERATE
    outputgen5: FOR k1 IN 0 TO 3 GENERATE
      w_signed(k, k1) <= signed(w(k, k1));
    END GENERATE;
  END GENERATE;

  c11_wGEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    c11_wGEN_LABEL: FOR d0 IN 0 TO 1 GENERATE
      c11_w(d0 + (d1 * 2)) <= w_signed(d0, d1);
    END GENERATE;
  END GENERATE;

  outputgen3: FOR k IN 0 TO 3 GENERATE
    a_signed(k) <= signed(a(k));
  END GENERATE;

  Transpose_out1 <= a_signed;

  selector_out(0) <= e(0);
  selector_out(1) <= e(1);
  selector_out(2) <= e(0);
  selector_out(3) <= e(1);
  selector_out(4) <= e(0);
  selector_out(5) <= e(1);
  selector_out(6) <= e(0);
  selector_out(7) <= e(1);

  outputgen2: FOR k IN 0 TO 7 GENERATE
    selector_out_1(k) <= signed(selector_out(k));
  END GENERATE;

  sGEN_LABEL: FOR d0 IN 0 TO 7 GENERATE
    s(d0) <= selector_out_1(d0);
  END GENERATE;

  selector_out_2(0) <= Transpose_out1(0);
  selector_out_2(1) <= Transpose_out1(0);
  selector_out_2(2) <= Transpose_out1(1);
  selector_out_2(3) <= Transpose_out1(1);
  selector_out_2(4) <= Transpose_out1(2);
  selector_out_2(5) <= Transpose_out1(2);
  selector_out_2(6) <= Transpose_out1(3);
  selector_out_2(7) <= Transpose_out1(3);

  s_1GEN_LABEL: FOR d0 IN 0 TO 7 GENERATE
    s_1(d0) <= selector_out_2(d0);
  END GENERATE;


  MMul_dot_product_out_gen: FOR t_02 IN 0 TO 7 GENERATE
    MMul_dot_product_out(t_02) <= s(t_02) * s_1(t_02);
  END GENERATE MMul_dot_product_out_gen;



  c7_Product_out1_gen: FOR t_03 IN 0 TO 7 GENERATE
    Product_cast(t_03) <= signed(resize(alpha_unsigned, 19));
    Product_mul_temp(t_03) <= Product_cast(t_03) * MMul_dot_product_out(t_03);
    c7_Product_out1(t_03) <= Product_mul_temp(t_03)(108 DOWNTO 0);
  END GENERATE c7_Product_out1_gen;



  c11_Subtract_out1_gen: FOR t_04 IN 0 TO 7 GENERATE
    Subtract_sub_cast(t_04) <= resize(c11_w(t_04) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 110);
    Subtract_sub_cast_1(t_04) <= resize(c7_Product_out1(t_04), 110);
    c11_Subtract_out1(t_04) <= Subtract_sub_cast(t_04) - Subtract_sub_cast_1(t_04);
  END GENERATE c11_Subtract_out1_gen;


  Subtract_out1GEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    Subtract_out1GEN_LABEL: FOR d0 IN 0 TO 1 GENERATE
      Subtract_out1(d0, d1) <= c11_Subtract_out1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  outputgen: FOR k IN 0 TO 1 GENERATE
    outputgen1: FOR k1 IN 0 TO 3 GENERATE
      w_1(k, k1) <= std_logic_vector(Subtract_out1(k, k1));
    END GENERATE;
  END GENERATE;

END rtl;

