-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Subsystem1.vhd
-- Created: 2022-05-21 11:54:13
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem1
-- Source Path: ANN/HDL_ANN/Train/Subsystem1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem1 IS
  PORT( a3                                :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        y                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        e3                                :   OUT   std_logic_vector(36 DOWNTO 0)  -- sfix37_En24
        );
END Subsystem1;


ARCHITECTURE rtl OF Subsystem1 IS

  -- Signals
  SIGNAL a3_signed                        : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL y_signed                         : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL Subtract_sub_cast                : signed(18 DOWNTO 0);  -- sfix19_En12
  SIGNAL Subtract_sub_cast_1              : signed(18 DOWNTO 0);  -- sfix19_En12
  SIGNAL Subtract_out1                    : signed(18 DOWNTO 0);  -- sfix19_En12
  SIGNAL Constant1_out1                   : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL Product1_out1                    : signed(36 DOWNTO 0);  -- sfix37_En24

BEGIN
  a3_signed <= signed(a3);

  y_signed <= signed(y);

  Subtract_sub_cast <= resize(a3_signed, 19);
  Subtract_sub_cast_1 <= resize(y_signed, 19);
  Subtract_out1 <= Subtract_sub_cast - Subtract_sub_cast_1;

  Constant1_out1 <= to_signed(16#02000#, 18);

  Product1_out1 <= Subtract_out1 * Constant1_out1;

  e3 <= std_logic_vector(Product1_out1);

END rtl;

