-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Subsystem2.vhd
-- Created: 2022-05-21 15:41:35
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem2
-- Source Path: ANN/HDL_ANN/Train/Subsystem2
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_ANN_pkg.ALL;

ENTITY Subsystem2 IS
  PORT( w                                 :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        a                                 :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        e                                 :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En24
        b                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        alpha                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        b_1                               :   OUT   std_logic_vector(55 DOWNTO 0);  -- sfix56_En42
        w_1                               :   OUT   vector_of_std_logic_vector74(0 TO 1)  -- sfix74_En54 [2]
        );
END Subsystem2;


ARCHITECTURE rtl OF Subsystem2 IS

  -- Signals
  SIGNAL b_signed                         : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL e_signed                         : signed(36 DOWNTO 0);  -- sfix37_En24
  SIGNAL alpha_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL Product1_cast                    : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL Product1_mul_temp                : signed(55 DOWNTO 0);  -- sfix56_En42
  SIGNAL Product1_out1                    : signed(54 DOWNTO 0);  -- sfix55_En42
  SIGNAL Subtract1_sub_cast               : signed(55 DOWNTO 0);  -- sfix56_En42
  SIGNAL Subtract1_sub_cast_1             : signed(55 DOWNTO 0);  -- sfix56_En42
  SIGNAL Subtract1_out1                   : signed(55 DOWNTO 0);  -- sfix56_En42
  SIGNAL w_signed                         : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL a_signed                         : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Transpose_out1                   : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL dw_out1                          : vector_of_signed55(0 TO 1);  -- sfix55_En36 [2]
  SIGNAL Product_cast                     : vector_of_signed19(0 TO 1);  -- sfix19_En18 [2]
  SIGNAL Product_mul_temp                 : vector_of_signed74(0 TO 1);  -- sfix74_En54 [2]
  SIGNAL Product_out1                     : vector_of_signed73(0 TO 1);  -- sfix73_En54 [2]
  SIGNAL Subtract_sub_cast                : vector_of_signed74(0 TO 1);  -- sfix74_En54 [2]
  SIGNAL Subtract_sub_cast_1              : vector_of_signed74(0 TO 1);  -- sfix74_En54 [2]
  SIGNAL Subtract_out1                    : vector_of_signed74(0 TO 1);  -- sfix74_En54 [2]

BEGIN
  b_signed <= signed(b);

  e_signed <= signed(e);

  alpha_unsigned <= unsigned(alpha);

  Product1_cast <= signed(resize(alpha_unsigned, 19));
  Product1_mul_temp <= e_signed * Product1_cast;
  Product1_out1 <= Product1_mul_temp(54 DOWNTO 0);

  Subtract1_sub_cast <= resize(b_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 56);
  Subtract1_sub_cast_1 <= resize(Product1_out1, 56);
  Subtract1_out1 <= Subtract1_sub_cast - Subtract1_sub_cast_1;

  b_1 <= std_logic_vector(Subtract1_out1);

  outputgen2: FOR k IN 0 TO 1 GENERATE
    w_signed(k) <= signed(w(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 1 GENERATE
    a_signed(k) <= signed(a(k));
  END GENERATE;

  Transpose_out1 <= a_signed;


  dw_out1_gen: FOR t_0 IN 0 TO 1 GENERATE
    dw_out1(t_0) <= e_signed * Transpose_out1(t_0);
  END GENERATE dw_out1_gen;



  Product_out1_gen: FOR t_01 IN 0 TO 1 GENERATE
    Product_cast(t_01) <= signed(resize(alpha_unsigned, 19));
    Product_mul_temp(t_01) <= Product_cast(t_01) * dw_out1(t_01);
    Product_out1(t_01) <= Product_mul_temp(t_01)(72 DOWNTO 0);
  END GENERATE Product_out1_gen;



  Subtract_out1_gen: FOR t_02 IN 0 TO 1 GENERATE
    Subtract_sub_cast(t_02) <= resize(w_signed(t_02) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 74);
    Subtract_sub_cast_1(t_02) <= resize(Product_out1(t_02), 74);
    Subtract_out1(t_02) <= Subtract_sub_cast(t_02) - Subtract_sub_cast_1(t_02);
  END GENERATE Subtract_out1_gen;


  outputgen: FOR k IN 0 TO 1 GENERATE
    w_1(k) <= std_logic_vector(Subtract_out1(k));
  END GENERATE;

END rtl;

