-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Subsystem.vhd
-- Created: 2022-05-21 11:54:13
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: ANN/HDL_ANN/Train/Subsystem
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_ANN_pkg.ALL;

ENTITY Subsystem IS
  PORT( e3                                :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En24
        z2                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        w3                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        e2                                :   OUT   vector_of_std_logic_vector73(0 TO 1)  -- sfix73_En48 [2]
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Signals
  SIGNAL w3_signed                        : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Transpose_out1                   : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL z2_0                             : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant1_out1                   : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL Constant_out1                    : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL Switch_out1_0                    : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL z2_1                             : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL switch_compare_2                 : std_logic;
  SIGNAL e3_signed                        : signed(36 DOWNTO 0);  -- sfix37_En24
  SIGNAL MatrixMultiply_out1              : vector_of_signed55(0 TO 1);  -- sfix55_En36 [2]
  SIGNAL Switch_out1_1                    : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL Switch_out1                      : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Product_out1                     : vector_of_signed73(0 TO 1);  -- sfix73_En48 [2]

BEGIN
  outputgen1: FOR k IN 0 TO 1 GENERATE
    w3_signed(k) <= signed(w3(k));
  END GENERATE;

  Transpose_out1 <= w3_signed;

  z2_0 <= signed(z2(0));

  
  switch_compare_1 <= '1' WHEN z2_0 > to_signed(16#00000#, 18) ELSE
      '0';

  Constant1_out1 <= to_signed(16#0019A#, 18);

  Constant_out1 <= to_signed(16#01000#, 18);

  
  Switch_out1_0 <= Constant1_out1 WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  z2_1 <= signed(z2(1));

  
  switch_compare_2 <= '1' WHEN z2_1 > to_signed(16#00000#, 18) ELSE
      '0';

  e3_signed <= signed(e3);


  MatrixMultiply_out1_gen: FOR t_0 IN 0 TO 1 GENERATE
    MatrixMultiply_out1(t_0) <= Transpose_out1(t_0) * e3_signed;
  END GENERATE MatrixMultiply_out1_gen;


  
  Switch_out1_1 <= Constant1_out1 WHEN switch_compare_2 = '0' ELSE
      Constant_out1;

  Switch_out1(0) <= Switch_out1_0;
  Switch_out1(1) <= Switch_out1_1;


  Product_out1_gen: FOR t_01 IN 0 TO 1 GENERATE
    Product_out1(t_01) <= MatrixMultiply_out1(t_01) * Switch_out1(t_01);
  END GENERATE Product_out1_gen;


  outputgen: FOR k IN 0 TO 1 GENERATE
    e2(k) <= std_logic_vector(Product_out1(k));
  END GENERATE;

END rtl;

