-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Subsystem2.vhd
-- Created: 2022-05-13 14:13:53
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem2
-- Source Path: ANN/HDL_ANN/Enabled Subsystem1/Subsystem2
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_ANN_pkg.ALL;

ENTITY Subsystem2 IS
  PORT( w3                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        a2                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        e3                                :   IN    std_logic_vector(18 DOWNTO 0);  -- sfix19_En12
        b3                                :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        alpha                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        updated_b3                        :   OUT   std_logic_vector(37 DOWNTO 0);  -- sfix38_En30
        updated_w3                        :   OUT   vector_of_std_logic_vector56(0 TO 1)  -- sfix56_En42 [2]
        );
END Subsystem2;


ARCHITECTURE rtl OF Subsystem2 IS

  -- Signals
  SIGNAL b3_signed                        : signed(17 DOWNTO 0);  -- sfix18_En12
  SIGNAL e3_signed                        : signed(18 DOWNTO 0);  -- sfix19_En12
  SIGNAL alpha_unsigned                   : unsigned(17 DOWNTO 0);  -- ufix18_En18
  SIGNAL Multiply_Add1_mul_cast           : signed(18 DOWNTO 0);  -- sfix19_En18
  SIGNAL Multiply_Add1_mul_mul_temp       : signed(37 DOWNTO 0);  -- sfix38_En30
  SIGNAL mulOutput                        : signed(36 DOWNTO 0);  -- sfix37_En30
  SIGNAL Multiply_Add1_add_sub_cast       : signed(37 DOWNTO 0);  -- sfix38_En30
  SIGNAL Multiply_Add1_add_sub_cast_1     : signed(37 DOWNTO 0);  -- sfix38_En30
  SIGNAL Multiply_Add1_out1               : signed(37 DOWNTO 0);  -- sfix38_En30
  SIGNAL w3_signed                        : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL a2_signed                        : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Transpose_out1                   : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL dw3_out1                         : vector_of_signed37(0 TO 1);  -- sfix37_En24 [2]
  SIGNAL Multiply_Add_mul_cast            : vector_of_signed19(0 TO 1);  -- sfix19_En18 [2]
  SIGNAL Multiply_Add_mul_mul_temp        : vector_of_signed56(0 TO 1);  -- sfix56_En42 [2]
  SIGNAL mulOutput_1                      : vector_of_signed55(0 TO 1);  -- sfix55_En42 [2]
  SIGNAL Multiply_Add_add_sub_cast        : vector_of_signed56(0 TO 1);  -- sfix56_En42 [2]
  SIGNAL Multiply_Add_add_sub_cast_1      : vector_of_signed56(0 TO 1);  -- sfix56_En42 [2]
  SIGNAL Multiply_Add_out1                : vector_of_signed56(0 TO 1);  -- sfix56_En42 [2]

BEGIN
  b3_signed <= signed(b3);

  e3_signed <= signed(e3);

  alpha_unsigned <= unsigned(alpha);

  Multiply_Add1_mul_cast <= signed(resize(alpha_unsigned, 19));
  Multiply_Add1_mul_mul_temp <= e3_signed * Multiply_Add1_mul_cast;
  mulOutput <= Multiply_Add1_mul_mul_temp(36 DOWNTO 0);

  Multiply_Add1_add_sub_cast <= resize(b3_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 38);
  Multiply_Add1_add_sub_cast_1 <= resize(mulOutput, 38);
  Multiply_Add1_out1 <= Multiply_Add1_add_sub_cast - Multiply_Add1_add_sub_cast_1;

  updated_b3 <= std_logic_vector(Multiply_Add1_out1);

  outputgen2: FOR k IN 0 TO 1 GENERATE
    w3_signed(k) <= signed(w3(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 1 GENERATE
    a2_signed(k) <= signed(a2(k));
  END GENERATE;

  Transpose_out1 <= a2_signed;


  dw3_out1_gen: FOR t_0 IN 0 TO 1 GENERATE
    dw3_out1(t_0) <= e3_signed * Transpose_out1(t_0);
  END GENERATE dw3_out1_gen;



  mulOutput_1_gen: FOR t_01 IN 0 TO 1 GENERATE
    Multiply_Add_mul_cast(t_01) <= signed(resize(alpha_unsigned, 19));
    Multiply_Add_mul_mul_temp(t_01) <= Multiply_Add_mul_cast(t_01) * dw3_out1(t_01);
    mulOutput_1(t_01) <= Multiply_Add_mul_mul_temp(t_01)(54 DOWNTO 0);
  END GENERATE mulOutput_1_gen;



  Multiply_Add_out1_gen: FOR t_02 IN 0 TO 1 GENERATE
    Multiply_Add_add_sub_cast(t_02) <= resize(w3_signed(t_02) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 56);
    Multiply_Add_add_sub_cast_1(t_02) <= resize(mulOutput_1(t_02), 56);
    Multiply_Add_out1(t_02) <= Multiply_Add_add_sub_cast(t_02) - Multiply_Add_add_sub_cast_1(t_02);
  END GENERATE Multiply_Add_out1_gen;


  outputgen: FOR k IN 0 TO 1 GENERATE
    updated_w3(k) <= std_logic_vector(Multiply_Add_out1(k));
  END GENERATE;

END rtl;

