-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ANN\Train.vhd
-- Created: 2022-05-21 15:41:35
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Train
-- Source Path: ANN/HDL_ANN/Train
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_ANN_pkg.ALL;

ENTITY Train IS
  PORT( x                                 :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        y                                 :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        a1                                :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
        a2                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        a3                                :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        z1                                :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
        z2                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        w1                                :   IN    matrix_of_std_logic_vector18(0 TO 3, 0 TO 1);  -- sfix18_En12 [4x2]
        w2                                :   IN    matrix_of_std_logic_vector18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
        w3                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        b1                                :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
        b2                                :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        b3                                :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
        alpha                             :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
        Enable                            :   IN    std_logic;
        updated_w1                        :   OUT   matrix_of_std_logic_vector18(0 TO 3, 0 TO 1);  -- sfix18_En12 [4x2]
        updated_w2                        :   OUT   matrix_of_std_logic_vector18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
        updated_w3                        :   OUT   vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        updated_b1                        :   OUT   vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
        updated_b2                        :   OUT   vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
        updated_b3                        :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En12
        );
END Train;


ARCHITECTURE rtl OF Train IS

  -- Component Declarations
  COMPONENT Subsystem1
    PORT( a3                              :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
          y                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
          e3                              :   OUT   std_logic_vector(36 DOWNTO 0)  -- sfix37_En24
          );
  END COMPONENT;

  COMPONENT Subsystem
    PORT( e3                              :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En24
          z2                              :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          w3                              :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          e2                              :   OUT   vector_of_std_logic_vector73(0 TO 1)  -- sfix73_En48 [2]
          );
  END COMPONENT;

  COMPONENT Subsystem4
    PORT( e2                              :   IN    vector_of_std_logic_vector73(0 TO 1);  -- sfix73_En48 [2]
          z1                              :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
          w2                              :   IN    matrix_of_std_logic_vector18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
          e1                              :   OUT   vector_of_std_logic_vector91(0 TO 3)  -- sfix91_En60 [4]
          );
  END COMPONENT;

  COMPONENT Subsystem_Reference1
    PORT( w                               :   IN    matrix_of_std_logic_vector18(0 TO 3, 0 TO 1);  -- sfix18_En12 [4x2]
          a                               :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          e                               :   IN    vector_of_std_logic_vector91(0 TO 3);  -- sfix91_En60 [4]
          b                               :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
          alpha                           :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          b_1                             :   OUT   vector_of_std_logic_vector110(0 TO 3);  -- sfix110_En78 [4]
          w_1                             :   OUT   matrix_of_std_logic_vector128(0 TO 3, 0 TO 1)  -- sfix128_En90 [4x2]
          );
  END COMPONENT;

  COMPONENT Subsystem_Reference
    PORT( w                               :   IN    matrix_of_std_logic_vector18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
          a                               :   IN    vector_of_std_logic_vector18(0 TO 3);  -- sfix18_En12 [4]
          e                               :   IN    vector_of_std_logic_vector73(0 TO 1);  -- sfix73_En48 [2]
          b                               :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          alpha                           :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          b_1                             :   OUT   vector_of_std_logic_vector92(0 TO 1);  -- sfix92_En66 [2]
          w_1                             :   OUT   matrix_of_std_logic_vector110(0 TO 1, 0 TO 3)  -- sfix110_En78 [2x4]
          );
  END COMPONENT;

  COMPONENT Subsystem2
    PORT( w                               :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          a                               :   IN    vector_of_std_logic_vector18(0 TO 1);  -- sfix18_En12 [2]
          e                               :   IN    std_logic_vector(36 DOWNTO 0);  -- sfix37_En24
          b                               :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En12
          alpha                           :   IN    std_logic_vector(17 DOWNTO 0);  -- ufix18_En18
          b_1                             :   OUT   std_logic_vector(55 DOWNTO 0);  -- sfix56_En42
          w_1                             :   OUT   vector_of_std_logic_vector74(0 TO 1)  -- sfix74_En54 [2]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem1
    USE ENTITY work.Subsystem1(rtl);

  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  FOR ALL : Subsystem4
    USE ENTITY work.Subsystem4(rtl);

  FOR ALL : Subsystem_Reference1
    USE ENTITY work.Subsystem_Reference1(rtl);

  FOR ALL : Subsystem_Reference
    USE ENTITY work.Subsystem_Reference(rtl);

  FOR ALL : Subsystem2
    USE ENTITY work.Subsystem2(rtl);

  -- Signals
  SIGNAL Subsystem1_out1                  : std_logic_vector(36 DOWNTO 0);  -- ufix37
  SIGNAL Subsystem_out1                   : vector_of_std_logic_vector73(0 TO 1);  -- ufix73 [2]
  SIGNAL Subsystem4_out1                  : vector_of_std_logic_vector91(0 TO 3);  -- ufix91 [4]
  SIGNAL Subsystem_Reference1_out1        : vector_of_std_logic_vector110(0 TO 3);  -- ufix110 [4]
  SIGNAL Subsystem_Reference1_out2        : matrix_of_std_logic_vector128(0 TO 3, 0 TO 1);  -- ufix128 [4x2]
  SIGNAL Subsystem_Reference1_out2_signed : matrix_of_signed128(0 TO 3, 0 TO 1);  -- sfix128_En90 [4x2]
  SIGNAL c24_Subsystem_Reference1_out2    : vector_of_signed128(0 TO 7);  -- sfix128_En90 [8]
  SIGNAL c24_Data_Type_Conversion6_out1   : vector_of_signed18(0 TO 7);  -- sfix18_En12 [8]
  SIGNAL Data_Type_Conversion6_out1       : matrix_of_signed18(0 TO 3, 0 TO 1);  -- sfix18_En12 [4x2]
  SIGNAL Subsystem_Reference_out1         : vector_of_std_logic_vector92(0 TO 1);  -- ufix92 [2]
  SIGNAL Subsystem_Reference_out2         : matrix_of_std_logic_vector110(0 TO 1, 0 TO 3);  -- ufix110 [2x4]
  SIGNAL Subsystem_Reference_out2_signed  : matrix_of_signed110(0 TO 1, 0 TO 3);  -- sfix110_En78 [2x4]
  SIGNAL c22_Subsystem_Reference_out2     : vector_of_signed110(0 TO 7);  -- sfix110_En78 [8]
  SIGNAL c22_Data_Type_Conversion4_out1   : vector_of_signed18(0 TO 7);  -- sfix18_En12 [8]
  SIGNAL Data_Type_Conversion4_out1       : matrix_of_signed18(0 TO 1, 0 TO 3);  -- sfix18_En12 [2x4]
  SIGNAL Subsystem2_out1                  : std_logic_vector(55 DOWNTO 0);  -- ufix56
  SIGNAL Subsystem2_out2                  : vector_of_std_logic_vector74(0 TO 1);  -- ufix74 [2]
  SIGNAL Subsystem2_out2_signed           : vector_of_signed74(0 TO 1);  -- sfix74_En54 [2]
  SIGNAL Data_Type_Conversion3_out1       : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Subsystem_Reference1_out1_signed : vector_of_signed110(0 TO 3);  -- sfix110_En78 [4]
  SIGNAL Data_Type_Conversion_out1        : vector_of_signed18(0 TO 3);  -- sfix18_En12 [4]
  SIGNAL Subsystem_Reference_out1_signed  : vector_of_signed92(0 TO 1);  -- sfix92_En66 [2]
  SIGNAL Data_Type_Conversion1_out1       : vector_of_signed18(0 TO 1);  -- sfix18_En12 [2]
  SIGNAL Subsystem2_out1_signed           : signed(55 DOWNTO 0);  -- sfix56_En42
  SIGNAL Data_Type_Conversion2_out1       : signed(17 DOWNTO 0);  -- sfix18_En12

BEGIN
  u_Subsystem1 : Subsystem1
    PORT MAP( a3 => a3,  -- sfix18_En12
              y => y,  -- sfix18_En12
              e3 => Subsystem1_out1  -- sfix37_En24
              );

  u_Subsystem : Subsystem
    PORT MAP( e3 => Subsystem1_out1,  -- sfix37_En24
              z2 => z2,  -- sfix18_En12 [2]
              w3 => w3,  -- sfix18_En12 [2]
              e2 => Subsystem_out1  -- sfix73_En48 [2]
              );

  u_Subsystem4 : Subsystem4
    PORT MAP( e2 => Subsystem_out1,  -- sfix73_En48 [2]
              z1 => z1,  -- sfix18_En12 [4]
              w2 => w2,  -- sfix18_En12 [2x4]
              e1 => Subsystem4_out1  -- sfix91_En60 [4]
              );

  u_Subsystem_Reference1 : Subsystem_Reference1
    PORT MAP( w => w1,  -- sfix18_En12 [4x2]
              a => x,  -- sfix18_En12 [2]
              e => Subsystem4_out1,  -- sfix91_En60 [4]
              b => b1,  -- sfix18_En12 [4]
              alpha => alpha,  -- ufix18_En18
              b_1 => Subsystem_Reference1_out1,  -- sfix110_En78 [4]
              w_1 => Subsystem_Reference1_out2  -- sfix128_En90 [4x2]
              );

  u_Subsystem_Reference : Subsystem_Reference
    PORT MAP( w => w2,  -- sfix18_En12 [2x4]
              a => a1,  -- sfix18_En12 [4]
              e => Subsystem_out1,  -- sfix73_En48 [2]
              b => b2,  -- sfix18_En12 [2]
              alpha => alpha,  -- ufix18_En18
              b_1 => Subsystem_Reference_out1,  -- sfix92_En66 [2]
              w_1 => Subsystem_Reference_out2  -- sfix110_En78 [2x4]
              );

  u_Subsystem2 : Subsystem2
    PORT MAP( w => w3,  -- sfix18_En12 [2]
              a => a2,  -- sfix18_En12 [2]
              e => Subsystem1_out1,  -- sfix37_En24
              b => b3,  -- sfix18_En12
              alpha => alpha,  -- ufix18_En18
              b_1 => Subsystem2_out1,  -- sfix56_En42
              w_1 => Subsystem2_out2  -- sfix74_En54 [2]
              );

  outputgen12: FOR k IN 0 TO 3 GENERATE
    outputgen13: FOR k1 IN 0 TO 1 GENERATE
      Subsystem_Reference1_out2_signed(k, k1) <= signed(Subsystem_Reference1_out2(k, k1));
    END GENERATE;
  END GENERATE;

  c24_Subsystem_Reference1_out2GEN_LABEL1: FOR d1 IN 0 TO 1 GENERATE
    c24_Subsystem_Reference1_out2GEN_LABEL: FOR d0 IN 0 TO 3 GENERATE
      c24_Subsystem_Reference1_out2(d0 + (d1 * 4)) <= Subsystem_Reference1_out2_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  c24_Data_Type_Conversion6_out1_gen: FOR ii IN 0 TO 7 GENERATE
    c24_Data_Type_Conversion6_out1(ii) <= c24_Subsystem_Reference1_out2(ii)(95 DOWNTO 78);
  END GENERATE c24_Data_Type_Conversion6_out1_gen;


  Data_Type_Conversion6_out1GEN_LABEL1: FOR d1 IN 0 TO 1 GENERATE
    Data_Type_Conversion6_out1GEN_LABEL: FOR d0 IN 0 TO 3 GENERATE
      Data_Type_Conversion6_out1(d0, d1) <= c24_Data_Type_Conversion6_out1(d0 + (d1 * 4));
    END GENERATE;
  END GENERATE;

  outputgen10: FOR k IN 0 TO 3 GENERATE
    outputgen11: FOR k1 IN 0 TO 1 GENERATE
      updated_w1(k, k1) <= std_logic_vector(Data_Type_Conversion6_out1(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen8: FOR k IN 0 TO 1 GENERATE
    outputgen9: FOR k1 IN 0 TO 3 GENERATE
      Subsystem_Reference_out2_signed(k, k1) <= signed(Subsystem_Reference_out2(k, k1));
    END GENERATE;
  END GENERATE;

  c22_Subsystem_Reference_out2GEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    c22_Subsystem_Reference_out2GEN_LABEL: FOR d0 IN 0 TO 1 GENERATE
      c22_Subsystem_Reference_out2(d0 + (d1 * 2)) <= Subsystem_Reference_out2_signed(d0, d1);
    END GENERATE;
  END GENERATE;


  c22_Data_Type_Conversion4_out1_gen: FOR ii1 IN 0 TO 7 GENERATE
    c22_Data_Type_Conversion4_out1(ii1) <= c22_Subsystem_Reference_out2(ii1)(83 DOWNTO 66);
  END GENERATE c22_Data_Type_Conversion4_out1_gen;


  Data_Type_Conversion4_out1GEN_LABEL1: FOR d1 IN 0 TO 3 GENERATE
    Data_Type_Conversion4_out1GEN_LABEL: FOR d0 IN 0 TO 1 GENERATE
      Data_Type_Conversion4_out1(d0, d1) <= c22_Data_Type_Conversion4_out1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  outputgen6: FOR k IN 0 TO 1 GENERATE
    outputgen7: FOR k1 IN 0 TO 3 GENERATE
      updated_w2(k, k1) <= std_logic_vector(Data_Type_Conversion4_out1(k, k1));
    END GENERATE;
  END GENERATE;

  outputgen5: FOR k IN 0 TO 1 GENERATE
    Subsystem2_out2_signed(k) <= signed(Subsystem2_out2(k));
  END GENERATE;


  Data_Type_Conversion3_out1_gen: FOR ii2 IN 0 TO 1 GENERATE
    Data_Type_Conversion3_out1(ii2) <= Subsystem2_out2_signed(ii2)(59 DOWNTO 42);
  END GENERATE Data_Type_Conversion3_out1_gen;


  outputgen4: FOR k IN 0 TO 1 GENERATE
    updated_w3(k) <= std_logic_vector(Data_Type_Conversion3_out1(k));
  END GENERATE;

  outputgen3: FOR k IN 0 TO 3 GENERATE
    Subsystem_Reference1_out1_signed(k) <= signed(Subsystem_Reference1_out1(k));
  END GENERATE;


  Data_Type_Conversion_out1_gen: FOR ii3 IN 0 TO 3 GENERATE
    Data_Type_Conversion_out1(ii3) <= Subsystem_Reference1_out1_signed(ii3)(83 DOWNTO 66);
  END GENERATE Data_Type_Conversion_out1_gen;


  outputgen2: FOR k IN 0 TO 3 GENERATE
    updated_b1(k) <= std_logic_vector(Data_Type_Conversion_out1(k));
  END GENERATE;

  outputgen1: FOR k IN 0 TO 1 GENERATE
    Subsystem_Reference_out1_signed(k) <= signed(Subsystem_Reference_out1(k));
  END GENERATE;


  Data_Type_Conversion1_out1_gen: FOR ii4 IN 0 TO 1 GENERATE
    Data_Type_Conversion1_out1(ii4) <= Subsystem_Reference_out1_signed(ii4)(71 DOWNTO 54);
  END GENERATE Data_Type_Conversion1_out1_gen;


  outputgen: FOR k IN 0 TO 1 GENERATE
    updated_b2(k) <= std_logic_vector(Data_Type_Conversion1_out1(k));
  END GENERATE;

  Subsystem2_out1_signed <= signed(Subsystem2_out1);

  Data_Type_Conversion2_out1 <= Subsystem2_out1_signed(47 DOWNTO 30);

  updated_b3 <= std_logic_vector(Data_Type_Conversion2_out1);


END rtl;

