%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [out_h1,w_h1,out_h2,w_h2,output] = forwardProp2_wrapper_fixpt(weights_11,weights_12,weights_13,weights_14,weights_21,weights_22,weights_3,input)
    fm = get_fimath();
    weights_11_in = fi( weights_11, 1, 14, 10, fm );
    weights_12_in = fi( weights_12, 1, 14, 10, fm );
    weights_13_in = fi( weights_13, 1, 14, 10, fm );
    weights_14_in = fi( weights_14, 1, 14, 10, fm );
    weights_21_in = fi( weights_21, 1, 14, 10, fm );
    weights_22_in = fi( weights_22, 1, 14, 10, fm );
    weights_3_in = fi( weights_3, 1, 14, 10, fm );
    input_in = fi( input, 1, 14, 4, fm );
    [out_h1_out,w_h1_out,out_h2_out,w_h2_out,output_out] = forwardProp2_fixpt( weights_11_in, weights_12_in, weights_13_in, weights_14_in, weights_21_in, weights_22_in, weights_3_in, input_in );
    out_h1 = double( out_h1_out );
    w_h1 = double( w_h1_out );
    out_h2 = double( out_h2_out );
    w_h2 = double( w_h2_out );
    output = double( output_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
